on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: discordtemp.azurecr.io
        username: ${{ secrets.acr_discordtemp_username }}
        password: ${{ secrets.acr_discordtemp_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t discordtemp.azurecr.io/aksdev33442:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push discordtemp.azurecr.io/aksdev33442:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdev33442_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep starbound | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace starbound`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: starbound
        container-registry-url: discordtemp.azurecr.io
        container-registry-username: ${{ secrets.acr_discordtemp_username }}
        container-registry-password: ${{ secrets.acr_discordtemp_password }}
        secret-name: aksdev33442dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: starbound
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          discordtemp.azurecr.io/aksdev33442:${{ github.sha }}
        imagepullsecrets: |
          aksdev33442dockerauth
